name: absensi_app
description: Aplikasi absensi sederhana dengan login dan dashboard (API).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  geolocator: ^14.0.0
  excel: ^4.0.6
  path_provider: ^2.1.4
  share_plus: ^11.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
